version: "3.8"

services:
  db: 
    container_name: postgres-db
    build: 
      context: ./db
    environment:
      PGDATA: /data
      POSTGRES_INITDB_ARGS: "--lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      POSTGRES_USERNAME: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports: 
      - 1234:5432

  node:
    container_name: app
    build: 
      context: ./../
      dockerfile: ./docker-compose/app/Dockerfile
    environment: 
      POSTGRES_USERNAME: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      DB_HOST: "db"
      DB_PORT: 5432
    ports:
      - 3000:3000
    